#ifndef ENUMS_H
#define ENUMS_H

enum {
    HELLO_REASON=0,
    SYSCALL_REASON,
    HALT_REASON,
    ILLEGAL_OPCODE_REASON,
    GPIO_SET_PINMODE_REASON,
    GPIO_SET_PINOUT_REASON,
    GPIO_SET_PINPULL_REASON,
    GPIO_GET_PINSTATE_REASON,
    ADC_ILLEGAL_CHANNEL_REASON,
    DMA_CHANNEL_CLAIMED_REASON,
    KEYBOARD_BUFFER_OVERFLOW_REASON
};

#endif 